@startuml

start
:Start page;
if (Browse existing Carport designs?) then (yes)
  :Browse carports;

elseif (Create Own Carport?) then (yes)
  :Find measurement;
  :Decide on Roof tiles;
  :Enter your contact info;
  :Send Carport Design to Fog for review;
  :Show order details;
  :Get email on Order status;
  if (Crreate user to see order on orderpage) then (yes)
  :Create password;
  :Login;
  else (no)
  :continue browsin;
  endif

elseif (Log in as Admin?) then (yes)
  :Enter Admin password and Username;
  if (Admin Logged In?) then (yes)
    :View Admin page;
    :See All Orders;
    :See Stock list;
    :Add Material;
  else (no)
    :Prøv igen;
    stop

  endif

   elseif (:Login as user;) then (yes)
    :Indtast brugernavn og adgangskode;
    if(See your order) then (yes)
    :show order details;
    :Change your contact information;
    else (no)
    :Buy new Carport;
    :Find measurement;
      :Decide on Roof tiles;
      :Enter your contact info;
      :Send Carport Design to Fog for review;
      :Show order details;
      :Get email on Order status;


@enduml
