@startuml
'https://plantuml.com/class-diagram



object Carport
object Rem
object Spær
object Materiale
object Skur
object Længde
object Bredde

object Sten
object Træ
object Aluminium

Materiale <|-- Sten: is-a
Materiale <|-- Træ: is-a
Materiale <|-- Aluminium: is-a

Carport *-- Rem: has-a
Carport *-- Spær: has-a
Carport *-- Skur: has-a

Carport <|-- Længde: is-a
Carport <|-- Bredde: is-a

Skur <|-- Materiale: is-a
Spær <|-- Materiale: is-a
Rem <|-- Materiale: is-a








@enduml