@startuml
'https://plantuml.com/state-diagram

left to right direction

[*] --> Index: On page load

Index --> Login: On click: Login
Index --> OrderCarport: On click: Customize

Login --> Index: On successful login
Login --> Register: On click: Register

Register --> Login: On successful registration
Register --> Register: on failed registration

OrderCarport --> OrderUserDetails: On click: Continue
OrderUserDetails --> OrderConfirmation: On click: Order




@enduml